version: '3.2'

name: jacq

services:
  port:
    container_name: port
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
