#cloud-config
# Check: cloud-init status --wait
# https://cloudinit.readthedocs.io/en/latest/

fqdn: jacq.cc
hostname: jacq.cc
locale: en_AU.UTF-8
timezone: Australia/Brisbane

manage-resolv-conf: true
resolv_conf:
  nameservers: ["1.1.1.1", "1.0.0.1"]

users:
  # 🔥 UPDATE USER
  - default
  - name: rj
    lock_passwd: true
    groups: sudo, users, admin, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    # Whether to disable password logins for the user.
    lock_passwd: true
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPh+R5aHphuQlIQ6Eh8STTH9gqD9mS5lLWhWpZnsZkKh r@jacq.cc"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhR9/6S+oIFLOxFWsMm4iIpKUBa8vcJ62CS4SwHJVAt r@jacq.cc"

# write_files:
#   - path: /home/rj/.bash_aliases

# files:
#   - path: /home/rj/.bash_aliases
#     source: .bash_aliases
#   - path: /home/rj/compose.yaml
#     source: compose.yaml

# https://launchpad.net/ubuntu/+archivemirrors
# sudo sed -i 's/http:\/\/us.archive.ubuntu.com/http:\/\/sg.archive.ubuntu.com/' /etc/apt/sources.list
# Better docs: https://github.com/canonical/curtin/blob/master/examples/apt-source.yaml
# -> https://curtin.readthedocs.io/en/latest/topics/apt_source.html#
# https://cloudinit.readthedocs.io/en/latest/reference/yaml_examples/apt.html
# Ubuntu sources directory: /etc/apt/sources.list or /etc/apt/sources.list.d/
apt:
  preserve_sources_list: false
  primary:
    - arches: [default]
      uri: http://sg.archive.ubuntu.com/ubuntu/
#       search:
#         # Singapore  
#         - http://sg.archive.ubuntu.com/ubuntu/
#         - http://mirror.sg.gs/ubuntu/
#         # Australia
#         # - https://mirror.aarnet.edu.au/ubuntu/
#         # - http://au.archive.ubuntu.com/ubuntu

packages:
  - curl
  - mpack
  - sshguard
  - ufw
package_update: true
package_upgrade: true

runcmd:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

  # ufw
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow http
  - ufw allow https
  # Custom SSH port, instead of 22
  - ufw limit 51265
  - ufw enable

  # sshd_config deny
  - sed -i 's/#\?\(PermitRootLogin\s*\).*$/\1 no/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(PasswordAuthentication\s*\).*$/\1 no/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(KbdInteractiveAuthentication\s*\).*$/\1 no/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(ChallengeResponseAuthentication\s*\).*$/\1 no/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(X11Forwarding\s*\).*$/\1 no/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(AllowAgentForwarding\s*\).*$/\1 no/' /etc/ssh/sshd_config

  # sshd_config allow
  - sed -i 's/#\?\(Port\s*\).*$/\1 51265/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(AllowTcpForwarding\s*\).*$/\1 yes/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(MaxAuthTries\s*\).*$/\1 2/' /etc/ssh/sshd_config
  - sed -i 's/#\?\(AuthorizedKeysFile\s*\).*$/\1 .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers rj' /etc/ssh/sshd_config

  # docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh ./get-docker.sh
  - usermod -aG docker rj
  - systemctl enable docker
  - systemctl enable containerd
  - mkdir -p /home/rj/.local/bin
  - sudo runuser -l rj -c "curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"
  - rm -f /get-docker.sh

  # Extract files in this directory from the MIME message
  - sudo munpack -f /var/lib/cloud/instance/user-data.txt -C /tmp
  - mv /tmp/.bash_aliases /home/rj/.bash_aliases

  - reboot
